let data = {
    students: {
      name_bangla: "শিক্ষার্থীর নাম (বাংলায়)",
      name_english: "Student Name (English)",
      birth_registration_number: "জন্ম নিবন্ধন নম্বর",
      date_of_birth: "জন্ম তারিখ",
      birth_district: "জন্মস্থান জেলা",
      gender: "জেন্ডার",
      nationality: "জাতীয়তা",
      religion: "ধর্ম",
      desired_class: "যে শ্রেণীতে ভর্তি হতে ইচ্ছুক",
      marital_status: "বৈবাহিক অবস্থা",
      blood_group: "রক্তের গ্রুপ",
      minority_ethnicity: "ক্ষুদ্র নৃ-গোষ্টি কিনা",
      photo: "শিক্ষার্থীর ছবি (পাসপোর্ট সাইজের ছবি)",
      previous_exam_info: [
        {
          class_name: "শ্রেণীর নাম",
          exam_name: "পরীক্ষার নাম",
          result: "পরীক্ষার ফলাফল",
          exam_time: "পরীক্ষার সময়",
          institution_name: "শিক্ষা/প্রতিষ্ঠানের নাম",
        },
      ],
      hobbies: "শিক্ষার্থীর শখ",
      favorite_books: "শিক্ষার্থীর পছন্দের বই",
      financial_assistance_needed:
        "শিক্ষার্থী উপবৃত্তি প্রয়োজন (ড্রপ ডাউনে হ্যাঁ অথবা না)",
      opinion: "শিক্ষার্থীর মতামত",
    },
    mother_info: {
      name_bangla: "মাতার নাম (বাংলায়)",
      name_english: "Mother's Name (English)",
      nid: "মাতার এনআইডি",
      date_of_birth: "মাতার জন্ম তারিখ",
      birth_registration: "মাতার জন্ম নিবন্ধন",
      phone_number: "মাতার ফোন নাম্বার",
      profession: "মাতার পেশা",
      year_of_death: "মাতা মৃত হলে মৃত্যুর সাল",
    },
    father_info: {
      name_bangla: "পিতার নাম (বাংলায়)",
      name_english: "Father's Name (English)",
      nid: "পিতার এনআইডি",
      date_of_birth: "পিতার জন্ম তারিখ",
      birth_registration: "পিতার জন্ম নিবন্ধন",
      phone_number: "পিতার ফোন নাম্বার",
      profession: "পিতার পেশা",
      year_of_death: "পিতা মৃত হলে মৃত্যুর সাল",
    },
    current_address: {
      division: "বিভাগ",
      district: "জেলা",
      sub_district: "উপজেলা/থানা",
      city_corporation: "সিটি কর্পোরেশন/পৌরসভা",
      union: "ইউনিয়ন",
      ward_number: "ওয়ার্ড নম্বর",
      mouza: "মৌজা",
      village: "গ্রাম/মহল্লা/রাস্তার নাম ও নম্বর",
      house_house_holding_number: "বাসার হোল্ডিং নম্বর",
      post_office: "ডাকঘর",
      postal_code: "পোস্ট কোড",
    },
    permanent_address: {
      division: "বিভাগ",
      district: "জেলা",
      sub_district: "উপজেলা/থানা",
      city_corporation: "সিটি কর্পোরেশন/পৌরসভা",
      union: "ইউনিয়ন",
      ward_number: "ওয়ার্ড নম্বর",
      mouza: "মৌজা",
      village: "গ্রাম/মহল্লা/রাস্তার নাম ও নম্বর",
      house_house_holding_number: "বাসার হোল্ডিং নম্বর",
      post_office: "ডাকঘর",
      postal_code: "পোস্ট কোড",
    },
    other_guardian_info: {
      name: "অভিভাবকের নাম",
      nid: "অভিভাবকের এনআইডি",
      occupation: "অভিভাবকের পেশা",
      relationship: "অভিভাবকের সাথে শিক্ষার্থীদের সম্পর্ক",
      number: "অভিভাবকের ফোন নাম্বার",
    },
  };